version: "2"

services:
  debug:
    build: .
    command: npm run debug
    volumes:
      - ./:/server
    ports:
      - "56789:80"
      - "9222:9222"
    environment:
      # - IMGSRV_DOMAINS=www.vistaprint.com,upload.wikimedia.org
      - NODE_TLS_REJECT_UNAUTHORIZED=0
  web:
    build: .
    command: npm start
    ports:
      - "56789:80"
    environment:
      # - IMGSRV_DOMAINS=www.vistaprint.com,upload.wikimedia.org
      - NODE_TLS_REJECT_UNAUTHORIZED=0